export default {
  index: 'Overview',
  '---1': { type: 'separator', title: 'Pipeline v2' },
  brainstorm: 'Brainstorm (async)',
  'research-sessions': 'Research Sessions',
  'content-drafts': 'Content Drafts',
  bulk: 'Bulk Generation',
  'canonical-core': 'Canonical Core',
  ideas: 'Ideas Library',
  '---2': { type: 'separator', title: 'Billing & usage' },
  billing: 'Billing (Stripe)',
  usage: 'Usage Analytics',
  '---3': { type: 'separator', title: 'Agents & AI' },
  ai: 'AI Config',
  '---4': { type: 'separator', title: 'Integrations' },
  wordpress: 'WordPress',
  '---5': { type: 'separator', title: 'Legacy (v1)' },
  projects: 'Projects',
  research: 'Research Archives',
  stages: 'Stages',
  blogs: 'Blogs',
  videos: 'Videos',
  podcasts: 'Podcasts',
  shorts: 'Shorts',
  templates: 'Templates',
  assets: 'Assets',
  users: 'Users (Admin)',
}
