// GENERATED by `npm run db:types` — DO NOT EDIT BY HAND
// Run `npm run db:types` after any schema migration to regenerate.
export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};
