export default {
  index: 'Overview',
  '---1': { type: 'separator', title: 'Creation flow (v2)' },
  'create-content': 'Create Content (wizard)',
  ideas: 'Ideas',
  research: 'Research',
  '---2': { type: 'separator', title: 'Formats' },
  blogs: 'Blogs',
  videos: 'Videos',
  shorts: 'Shorts',
  podcasts: 'Podcasts',
  '---3': { type: 'separator', title: 'Media & publishing' },
  'image-bank': 'Image Bank',
  wordpress: 'WordPress',
  '---4': { type: 'separator', title: 'Account & plan' },
  billing: 'Plan & credits',
  usage: 'Usage & cost',
  settings: 'Settings (admin)',
  '---5': { type: 'separator', title: 'Legacy' },
  projects: 'Projects (v1)',
  templates: 'Templates',
}
