export default {
  index: 'Visão Geral',
  '---1': { type: 'separator', title: 'Fluxo de criação (v2)' },
  'create-content': 'Create Content (wizard)',
  ideas: 'Ideias',
  research: 'Pesquisa',
  '---2': { type: 'separator', title: 'Formatos' },
  blogs: 'Blogs',
  videos: 'Vídeos',
  shorts: 'Shorts',
  podcasts: 'Podcasts',
  '---3': { type: 'separator', title: 'Mídia & publicação' },
  'image-bank': 'Image Bank',
  wordpress: 'WordPress',
  '---4': { type: 'separator', title: 'Conta & plano' },
  billing: 'Plano & créditos',
  usage: 'Uso & custo',
  settings: 'Settings (admin)',
  '---5': { type: 'separator', title: 'Legado' },
  projects: 'Projetos (v1)',
  templates: 'Templates',
}
