#!/usr/bin/env tsx
/**
 * Reads agents/agent-{n}-{stage}.md and generates supabase/seed.sql
 * No frontmatter required — stage derived from filename, name from first h1.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const AGENTS_DIR = join(process.cwd(), 'agents');
const OUT = join(process.cwd(), 'supabase', 'seed.sql');
// Matches agent-1-brainstorm.md, agent-3a-content-core.md, agent-3b-blog.md, etc.
const AGENT_RE = /^agent-(\d+)([a-z]?)-(.+)\.md$/;

const STAGE_BY_NUM: Record<string, string> = {
  '1': 'brainstorm',
  '2': 'research',
  '3': 'production',
  '4': 'review',
  '5': 'assets',
};

function dollarQuote(s: string): string {
  let tag = 'bt';
  let n = 0;
  while (s.includes(`$${tag}$`)) tag = `bt${++n}`;
  return `$${tag}$${s}$${tag}$`;
}

const files = readdirSync(AGENTS_DIR)
  .filter(f => AGENT_RE.test(f))
  .sort();

if (files.length === 0) {
  console.error('No agent files found in agents/ — expected agent-{n}-{stage}.md');
  process.exit(1);
}

const inserts = files.map(f => {
  const [, agentNum, subLetter, suffix] = AGENT_RE.exec(f)!;
  const stage = STAGE_BY_NUM[agentNum] ?? 'unknown';
  // slug: unique identifier — use suffix for 3a/3b variants, stage name otherwise.
  const slug = subLetter ? suffix : stage;
  const id = `agent-${agentNum}${subLetter}-${suffix}`;
  const instructions = readFileSync(join(AGENTS_DIR, f), 'utf8').trim();
  const nameMatch = instructions.match(/^#\s+Agent\s+[\d\w]+:\s+(.+)/m);
  const name = nameMatch ? nameMatch[1].trim() : `Agent ${agentNum}${subLetter}`;

  return [
    `insert into public.agent_prompts (id, name, slug, stage, instructions, created_at, updated_at)`,
    `values (`,
    `  ${dollarQuote(id)},`,
    `  ${dollarQuote(name)},`,
    `  ${dollarQuote(slug)},`,
    `  ${dollarQuote(stage)},`,
    `  ${dollarQuote(instructions)},`,
    `  now(),`,
    `  now()`,
    `)`,
    `on conflict (slug) do update set`,
    `  name = excluded.name,`,
    `  instructions = excluded.instructions,`,
    `  updated_at = now();`,
  ].join('\n');
});

const header = [
  '-- GENERATED by scripts/generate-seed.ts — DO NOT EDIT BY HAND',
  '-- Source: agents/agent-*.md',
  '-- Regenerate: npm run db:seed',
  '',
].join('\n');

writeFileSync(OUT, header + '\n' + inserts.join('\n\n') + '\n');
console.log(`✓ Wrote ${inserts.length} agent_prompts inserts → supabase/seed.sql`);
