#!/usr/bin/env tsx
/**
 * Reads TypeScript agent definitions, assembles instructions,
 * and outputs:
 *   1. supabase/seed.sql (regenerated each run, used by `supabase db reset`)
 *   2. supabase/migrations/20260417210000_refresh_agent_prompts.sql (for remote db push)
 *
 * Run: npm run db:seed:agents
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { assembleInstructions } from '@brighttale/shared';
import { ALL_AGENTS } from './agents/index';

const REPO_ROOT = process.cwd();
const SEED_PATH = join(REPO_ROOT, 'supabase', 'seed.sql');
const MIGRATION_PATH = join(REPO_ROOT, 'supabase', 'migrations', '20260417210000_refresh_agent_prompts.sql');

function dollarQuote(s: string): string {
  let tag = 'bt';
  let n = 0;
  while (s.includes(`$${tag}$`)) tag = `bt${++n}`;
  return `$${tag}$${s}$${tag}$`;
}

function jsonQuote(obj: unknown): string {
  const json = JSON.stringify(obj);
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function generateUpsertSQL(): string {
  if (ALL_AGENTS.length === 0) {
    return '-- No agents defined. Populate scripts/agents/*.ts and rerun.\n';
  }

  const statements = ALL_AGENTS.map((agent) => {
    const instructions = assembleInstructions(agent.sections);
    const id = `agent-${agent.slug}`;
    return [
      `insert into public.agent_prompts (id, name, slug, stage, instructions, sections_json, recommended_provider, recommended_model, tools_json, created_at, updated_at)`,
      `values (`,
      `  ${dollarQuote(id)},`,
      `  ${dollarQuote(agent.name)},`,
      `  ${dollarQuote(agent.slug)},`,
      `  ${dollarQuote(agent.stage)},`,
      `  ${dollarQuote(instructions)},`,
      `  ${jsonQuote(agent.sections)},`,
      agent.recommendedProvider ? `  ${dollarQuote(agent.recommendedProvider)},` : `  null,`,
      agent.recommendedModel ? `  ${dollarQuote(agent.recommendedModel)},` : `  null,`,
      agent.tools && agent.tools.length > 0 ? `  ${jsonQuote(agent.tools)},` : `  '[]'::jsonb,`,
      `  now(),`,
      `  now()`,
      `)`,
      `on conflict (slug) do update set`,
      `  name = excluded.name,`,
      `  instructions = excluded.instructions,`,
      `  sections_json = excluded.sections_json,`,
      `  recommended_provider = excluded.recommended_provider,`,
      `  recommended_model = excluded.recommended_model,`,
      `  tools_json = excluded.tools_json,`,
      `  updated_at = now();`,
    ].join('\n');
  });

  return statements.join('\n\n') + '\n';
}

function main() {
  const sql = generateUpsertSQL();

  const header = `-- Generated by scripts/seed-agents.ts — DO NOT EDIT MANUALLY.
-- Source of truth: scripts/agents/*.ts
-- Run: npm run db:seed:agents

`;

  writeFileSync(SEED_PATH, header + sql);
  writeFileSync(MIGRATION_PATH, header + sql);

  console.log(`Wrote ${ALL_AGENTS.length} agents to:`);
  console.log(`  - ${SEED_PATH}`);
  console.log(`  - ${MIGRATION_PATH}`);
}

main();
