#!/usr/bin/env tsx
/**
 * Reads TypeScript agent definitions, assembles instructions,
 * and outputs:
 *   1. supabase/seed.sql (regenerated each run, used by `supabase db reset`)
 *   2. supabase/migrations/20260417210000_refresh_agent_prompts.sql (for remote db push)
 *
 * Run: npm run db:seed:agents
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { assembleInstructions } from '@brighttale/shared';
import { ALL_AGENTS } from './agents/index';

const REPO_ROOT = process.cwd();
const SEED_PATH = join(REPO_ROOT, 'supabase', 'seed.sql');
const MIGRATION_PATH = join(REPO_ROOT, 'supabase', 'migrations', '20260417210000_refresh_agent_prompts.sql');

function dollarQuote(s: string): string {
  let tag = 'bt';
  let n = 0;
  while (s.includes(`$${tag}$`)) tag = `bt${++n}`;
  return `$${tag}$${s}$${tag}$`;
}

function jsonQuote(obj: unknown): string {
  const json = JSON.stringify(obj);
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function generateUpsertSQL(): string {
  if (ALL_AGENTS.length === 0) {
    return '-- No agents defined. Populate scripts/agents/*.ts and rerun.\n';
  }

  const statements = ALL_AGENTS.map((agent) => {
    const instructions = assembleInstructions(agent.sections);
    const id = `agent-${agent.slug}`;
    return [
      `insert into public.agent_prompts (id, name, slug, stage, instructions, sections_json, recommended_provider, recommended_model, tools_json, created_at, updated_at)`,
      `values (`,
      `  ${dollarQuote(id)},`,
      `  ${dollarQuote(agent.name)},`,
      `  ${dollarQuote(agent.slug)},`,
      `  ${dollarQuote(agent.stage)},`,
      `  ${dollarQuote(instructions)},`,
      `  ${jsonQuote(agent.sections)},`,
      agent.recommendedProvider ? `  ${dollarQuote(agent.recommendedProvider)},` : `  null,`,
      agent.recommendedModel ? `  ${dollarQuote(agent.recommendedModel)},` : `  null,`,
      agent.tools && agent.tools.length > 0 ? `  ${jsonQuote(agent.tools)},` : `  '[]'::jsonb,`,
      `  now(),`,
      `  now()`,
      `)`,
      // Note: recommended_provider and recommended_model are intentionally NOT
      // overwritten on conflict. Those columns are admin-managed via
      // /zadmin/agents/[slug]/editor — the .ts agent definitions ship with null
      // and the seed only seeds them on first insert. Adding them to the SET
      // clause would wipe the admin's per-stage provider/model picks every regen.
      `on conflict (slug) do update set`,
      `  name = excluded.name,`,
      `  instructions = excluded.instructions,`,
      `  sections_json = excluded.sections_json,`,
      `  tools_json = excluded.tools_json,`,
      `  updated_at = now();`,
    ].join('\n');
  });

  return statements.join('\n\n') + '\n';
}

function main() {
  const sql = generateUpsertSQL();

  const header = `-- Generated by scripts/seed-agents.ts — DO NOT EDIT MANUALLY.
-- Source of truth: scripts/agents/*.ts
-- Run: npm run db:seed:agents

`;

  // Seed-only preamble: when supabase db reset runs seed.sql AFTER all
  // migrations the column already exists. Belt-and-suspenders.
  const seedPreamble = `-- Ensure tools_json column exists (referenced by the INSERTs below).
ALTER TABLE public.agent_prompts ADD COLUMN IF NOT EXISTS tools_json JSONB NOT NULL DEFAULT '[]'::jsonb;

`;

  // Migration preamble: this file's timestamp (20260417210000) predates the
  // 20260430100000_agent_prompts_tools.sql migration that originally added
  // tools_json — so a fresh \`db:reset\` would fail without an idempotent
  // ALTER TABLE before the INSERTs.
  const migrationPreamble = `-- Idempotently ensure schema columns exist before INSERT — protects local
-- \`db:reset\` (strict timestamp order) when this regenerated file predates
-- the 20260430100000_agent_prompts_tools migration that originally added
-- tools_json. No-op on environments that already have the column.
ALTER TABLE public.agent_prompts ADD COLUMN IF NOT EXISTS tools_json JSONB NOT NULL DEFAULT '[]'::jsonb;

`;

  writeFileSync(SEED_PATH, header + seedPreamble + sql);
  writeFileSync(MIGRATION_PATH, header + migrationPreamble + sql);

  console.log(`Wrote ${ALL_AGENTS.length} agents to:`);
  console.log(`  - ${SEED_PATH}`);
  console.log(`  - ${MIGRATION_PATH}`);
}

main();
