#!/usr/bin/env tsx
/**
 * Reads PERSONAS definitions and appends upsert SQL to:
 *   1. supabase/seed.sql (appended after agents SQL)
 *   2. supabase/migrations/20260423000200_seed_personas.sql (for db push)
 *
 * Run: npm run db:seed:personas
 * IMPORTANT: always run db:seed:agents first (it overwrites seed.sql; this appends)
 */
import { appendFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { PERSONAS } from './agents/personas'

const REPO_ROOT = process.cwd()
const SEED_PATH = join(REPO_ROOT, 'supabase', 'seed.sql')
const MIGRATION_PATH = join(REPO_ROOT, 'supabase', 'migrations', '20260423000200_seed_personas.sql')

function dollarQuote(s: string): string {
  let tag = 'bt'
  let n = 0
  while (s.includes(`$${tag}$`)) tag = `bt${++n}`
  return `$${tag}$${s}$${tag}$`
}

function jsonbLiteral(obj: unknown): string {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`
}

function generateSQL(): string {
  const header = `\n-- Generated by scripts/seed-personas.ts — DO NOT EDIT MANUALLY.\n-- Run: npm run db:seed:personas\n\n`

  const statements = PERSONAS.map((p) =>
    [
      `insert into public.personas (slug, name, bio_short, bio_long, primary_domain, domain_lens, approved_categories, writing_voice_json, eeat_signals_json, soul_json, is_active, created_at, updated_at)`,
      `values (`,
      `  ${dollarQuote(p.slug)},`,
      `  ${dollarQuote(p.name)},`,
      `  ${dollarQuote(p.bioShort)},`,
      `  ${dollarQuote(p.bioLong)},`,
      `  ${dollarQuote(p.primaryDomain)},`,
      `  ${dollarQuote(p.domainLens)},`,
      `  ARRAY[${p.approvedCategories.map(dollarQuote).join(', ')}],`,
      `  ${jsonbLiteral(p.writingVoiceJson)},`,
      `  ${jsonbLiteral(p.eeatSignalsJson)},`,
      `  ${jsonbLiteral(p.soulJson)},`,
      `  true,`,
      `  now(),`,
      `  now()`,
      `)`,
      `on conflict (slug) do update set`,
      `  name = excluded.name,`,
      `  bio_short = excluded.bio_short,`,
      `  bio_long = excluded.bio_long,`,
      `  primary_domain = excluded.primary_domain,`,
      `  domain_lens = excluded.domain_lens,`,
      `  approved_categories = excluded.approved_categories,`,
      `  writing_voice_json = excluded.writing_voice_json,`,
      `  eeat_signals_json = excluded.eeat_signals_json,`,
      `  soul_json = excluded.soul_json,`,
      `  updated_at = now();`,
      `-- wp_author_id intentionally excluded from upsert (set manually)`,
    ].join('\n')
  )

  return header + statements.join('\n\n') + '\n'
}

function main() {
  const sql = generateSQL()
  appendFileSync(SEED_PATH, sql)
  writeFileSync(MIGRATION_PATH, sql)

  console.log(`Appended ${PERSONAS.length} personas to:`)
  console.log(`  - ${SEED_PATH}`)
  console.log(`  - ${MIGRATION_PATH}`)
}

main()
