/**
 * preSeedProductionOutput — write a synthetic draft_json onto the content_drafts
 * row and flip the production stage_run to status='completed' + outcome_json.
 *
 * Skips the real-AI production agent (which can hit "OpenAI tool call loop
 * exceeded maximum turns" against the configured gpt-5.4-mini model). Lets
 * downstream specs validate review+publish wiring without burning tokens or
 * fighting flake at the production step.
 */

const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL ?? ''
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? ''

function headers(prefer: string): HeadersInit {
  return {
    apikey: SERVICE_ROLE_KEY,
    Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    'Content-Type': 'application/json',
    Prefer: prefer,
  }
}

async function sbRequest<T = unknown>(
  method: 'GET' | 'POST' | 'PATCH',
  path: string,
  body?: unknown,
): Promise<T> {
  const url = `${SUPABASE_URL}/rest/v1/${path}`
  const res = await fetch(url, {
    method,
    headers: headers(method === 'PATCH' ? 'return=minimal' : 'return=representation'),
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`[preSeedProductionOutput] ${method} ${path} -> ${res.status}: ${text}`)
  }
  if (method === 'PATCH') return undefined as T
  return (await res.json()) as T
}

interface PreSeedProductionOutputOptions {
  projectId: string
  draftId: string
  /** content medium for synthetic draft shape (default: 'blog') */
  medium?: 'blog' | 'video' | 'shorts' | 'podcast'
}

const SYNTHETIC_BLOG_BODY = `# Pre-Seeded Blog Draft

This is a synthetic blog draft generated by the e2e test infrastructure to
bypass the production agent. The content is structured to satisfy the review
agent's basic checks (length, heading, paragraphs) so downstream stages can
exercise their real wiring.

## Section One

Real content engines depend on a tight feedback loop between research,
production, and review. When any one of those stages stalls, the entire
pipeline suffers. The canonical-onwards e2e validates that the orchestrator
correctly hands off state between engines under realistic conditions.

## Section Two

In step-by-step mode the user advances stages manually. Each engine reads
upstream results via the project context and writes its own result on
completion. The mirror layer keeps the legacy pipeline_state_json and the new
stage_runs table in sync.

## Conclusion

Validating this wiring with real AI everywhere is expensive and slow. Pre-
seeding the heavy stages lets us iterate quickly on the orchestration code
while still exercising real AI at the boundaries we care about.
`

export async function preSeedProductionOutput(
  opts: PreSeedProductionOutputOptions,
): Promise<void> {
  if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    throw new Error('[preSeedProductionOutput] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing')
  }

  const medium = opts.medium ?? 'blog'
  const now = new Date().toISOString()

  // Build a minimal draft_json shape per medium. ProductionEngine.extractProducedContent
  // reads `draft_json.<medium>.<key>` or top-level fallbacks.
  let draftJson: Record<string, unknown>
  switch (medium) {
    case 'blog':
      draftJson = {
        blog: {
          title: 'Pre-Seeded E2E Blog Draft',
          full_draft: SYNTHETIC_BLOG_BODY,
          word_count: 220,
        },
      }
      break
    case 'video':
      draftJson = {
        video: {
          script: SYNTHETIC_BLOG_BODY,
          teleprompter_script: SYNTHETIC_BLOG_BODY,
        },
      }
      break
    case 'shorts':
      draftJson = {
        shorts: [
          { hook: 'Pre-seeded short 1', script: 'Body 1' },
          { hook: 'Pre-seeded short 2', script: 'Body 2' },
        ],
      }
      break
    case 'podcast':
      draftJson = {
        podcast: { outline: SYNTHETIC_BLOG_BODY },
      }
      break
  }

  await sbRequest('PATCH', `content_drafts?id=eq.${opts.draftId}`, {
    draft_json: draftJson,
    status: 'draft',
    updated_at: now,
  })

  // Flip the production stage_run to completed. payload_ref already points at
  // the content_draft via splitDraftStageRuns. Add outcome_json so derive
  // sees a draft result with draftId.
  await sbRequest(
    'PATCH',
    `stage_runs?project_id=eq.${opts.projectId}&stage=eq.production`,
    {
      status: 'completed',
      finished_at: now,
      updated_at: now,
      outcome_json: {
        draftId: opts.draftId,
        draftTitle: (draftJson.blog as Record<string, unknown> | undefined)?.title ?? 'Pre-Seeded',
        draftContent: SYNTHETIC_BLOG_BODY,
      },
    },
  )
}
